Delete from Produtos where 1=1;

INSERT INTO `produtos` (`descricao`, `preco_venda`) VALUES
('Tênis Esportivo Masculino', 199.99),
('Tênis Casual Feminino', 149.90),
('Sapatênis Masculino Couro', 229.50),
('Sandália Rasteira Feminina', 79.90),
('Chinelo de Dedo Masculino', 29.90),
('Bota Adventure Masculina', 249.99),
('Sapato Social Masculino', 189.90),
('Mocassim Feminino', 159.99),
('Sapatilha Feminina Verniz', 99.90),
('Tênis Running Masculino', 299.99),
('Sapato Scarpin Feminino', 179.90),
('Chinelo Slide Feminino', 39.90),
('Bota Cano Curto Feminina', 269.90),
('Tênis Casual Masculino', 169.99),
('Sandália Anabela Feminina', 129.99),
('Sapato Oxford Masculino', 209.90),
('Sandália Gladiadora Feminina', 139.90),
('Tênis Skate Masculino', 149.90),
('Sapato Peep Toe Feminino', 189.90),
('Chinelo de Couro Masculino', 59.90),
('Bota Coturno Feminina', 299.90),
('Tênis Cano Alto Masculino', 199.90),
('Sapato Mule Feminino', 99.90),
('Sandália Plataforma Feminina', 149.90),
('Sapatênis Casual Masculino', 189.90),
('Bota Montaria Feminina', 349.90),
('Sapato Dockside Masculino', 179.90),
('Sapatilha Comfort Feminina', 89.90),
('Tênis Casual Infantil', 119.90),
('Chinelo Slide Masculino', 49.90),
('Sandália Casual Feminina', 109.90),
('Sapato Social Verniz Masculino', 239.90),
('Tênis Leve Feminino', 129.90),
('Bota de Couro Masculina', 399.90),
('Sapato Boneca Feminino', 149.90),
('Sapatilha Bordada Feminina', 79.90),
('Sandália Salto Bloco Feminina', 159.90),
('Tênis Slip On Masculino', 129.90),
('Sapato Social Feminino', 169.90),
('Chinelo Anatômico Masculino', 69.90),
('Bota Casual Masculina', 279.90),
('Tênis Multiesportivo Feminino', 179.90),
('Sapato Mocassim Infantil', 99.90),
('Tênis Estilo Chunky Feminino', 249.90),
('Sandália Esportiva Masculina', 109.90),
('Sapatilha de Ballet Feminina', 79.90),
('Bota Tática Masculina', 349.90),
('Sapato Loafer Feminino', 199.90),
('Tênis Basquete Masculino', 219.90),
('Chinelo Conforto Feminino', 39.90);



INSERT INTO `clientes` (`nome`, `cidade`, `uf`) VALUES
('João Silva', 'São Paulo', 'SP'),
('Maria Oliveira', 'Rio de Janeiro', 'RJ'),
('Pedro Santos', 'Belo Horizonte', 'MG'),
('Ana Costa', 'Curitiba', 'PR'),
('Lucas Almeida', 'Porto Alegre', 'RS'),
('Fernanda Lima', 'Salvador', 'BA'),
('Carlos Souza', 'Fortaleza', 'CE'),
('Juliana Ferreira', 'Brasília', 'DF'),
('Bruno Lima', 'Recife', 'PE'),
('Patrícia Araújo', 'Belém', 'PA'),
('Rafael Martins', 'Campinas', 'SP'),
('Daniela Rodrigues', 'Manaus', 'AM'),
('Thiago Barbosa', 'Goiânia', 'GO'),
('Larissa Melo', 'Florianópolis', 'SC'),
('Gabriel Ribeiro', 'São Luís', 'MA'),
('Isabela Ferreira', 'Vitória', 'ES'),
('Felipe Monteiro', 'João Pessoa', 'PB'),
('Aline Carvalho', 'Natal', 'RN'),
('André Gomes', 'Maceió', 'AL'),
('Sofia Batista', 'Campo Grande', 'MS'),
('Diego Pereira', 'Aracaju', 'SE'),
('Camila Rocha', 'Teresina', 'PI'),
('Mariana Nunes', 'Palmas', 'TO'),
('Rodrigo Mendes', 'Cuiabá', 'MT'),
('Letícia Farias', 'Porto Velho', 'RO'),
('Eduardo Duarte', 'Macapá', 'AP'),
('Carolina Souza', 'Boa Vista', 'RR'),
('Guilherme Oliveira', 'Rio Branco', 'AC'),
('Beatriz Silva', 'Campina Grande', 'PB'),
('Caio Fernandes', 'Vitória da Conquista', 'BA'),
('Paula Cruz', 'Blumenau', 'SC'),
('Fernando Cardoso', 'Cascavel', 'PR'),
('Ricardo Pinto', 'São José dos Campos', 'SP'),
('Manuela Gonçalves', 'Sorocaba', 'SP'),
('Júlia Nascimento', 'Niterói', 'RJ'),
('Leonardo Borges', 'São Bernardo do Campo', 'SP'),
('Clara Tavares', 'Santos', 'SP'),
('Miguel Campos', 'Osasco', 'SP'),
('Helena Monteiro', 'Diadema', 'SP'),
('Lucas Souza', 'Guarulhos', 'SP'),
('Ana Clara Lopes', 'São Caetano do Sul', 'SP'),
('João Pedro Pereira', 'Barueri', 'SP'),
('Marcos Andrade', 'Juclientesndiaí', 'SP'),
('Luiza Mendes', 'Ribeirão Preto', 'SP'),
('Enzo Alves', 'Piracicaba', 'SP'),
('Alice Pires', 'Franca', 'SP'),
('Lorenzo Dias', 'Carapicuíba', 'SP'),
('Davi Correia', 'Taubaté', 'SP'),
('Laura Teixeira', 'Bauru', 'SP');
